[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "HUfP36vmMYFkvV1e7EQd6cebP5PWikLSzzwv4Z78Wc6Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/id/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
